/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mp_privatefilm_JniUtils */

#ifndef _Included_com_mp_privatefilm_JniUtils
#define _Included_com_mp_privatefilm_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mp_privatefilm_JniUtils
 * Method:    getJniUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mp_privatefilm_JniUtils_getJniUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_mp_privatefilm_JniUtils
 * Method:    getJniEncryptKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mp_privatefilm_JniUtils_getJniEncryptKey
  (JNIEnv *, jclass);

/*
 * Class:     com_mp_privatefilm_JniUtils
 * Method:    getJniEncryptVector
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mp_privatefilm_JniUtils_getJniEncryptVector
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
